# Generated by Django 2.1.1 on 2018-11-26 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminuser',
            name='admin_rool',
            field=models.PositiveIntegerField(choices=[(0, '超级管理员'), (1, '类别总编'), (2, '策划总编'), (3, '管理员监查员')], default=0),
        ),
    ]
