# Generated by Django 2.1.1 on 2018-11-27 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0008_auto_20181127_2020'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
