# Generated by Django 2.1.1 on 2018-11-27 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0009_users_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='address',
            field=models.CharField(default='北京市 雄安区', max_length=64),
        ),
    ]
