# Generated by Django 2.1.1 on 2018-12-14 20:17

import DjangoUeditor.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0010_users_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ucontent',
            field=DjangoUeditor.models.UEditorField(blank=True, verbose_name='富文本新闻内容'),
        ),
    ]
