# Generated by Django 2.1.1 on 2018-12-16 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0011_article_ucontent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='media/tou.jpg', upload_to='%Y%m%d/'),
        ),
    ]
