# Generated by Django 2.1.1 on 2018-12-16 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0012_auto_20181216_0816'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='pubperson',
            field=models.CharField(default='----', max_length=64),
        ),
    ]
