# Generated by Django 2.1.1 on 2018-12-16 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0013_article_pubperson'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='积分账单', max_length=20)),
                ('score', models.CharField(default='+50', max_length=10)),
                ('cost_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='design.Users')),
            ],
        ),
    ]
