# Generated by Django 2.1.1 on 2018-12-17 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0015_comment'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Article')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='design.Users')),
            ],
        ),
    ]
