# Generated by Django 2.1.1 on 2018-12-18 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0018_connectuser_cname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectuser',
            name='cname',
            field=models.CharField(default='0', max_length=32),
        ),
    ]
