# Generated by Django 2.1.1 on 2018-12-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0019_auto_20181218_1516'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectuser',
            name='phone',
            field=models.CharField(max_length=11),
        ),
    ]
