# Generated by Django 2.1.1 on 2018-12-18 19:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0020_auto_20181218_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='System_log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(default='登录成功!', max_length=32)),
                ('username', models.CharField(default=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL), max_length=32)),
                ('pu_date', models.DateTimeField(auto_now_add=True)),
                ('IP', models.CharField(default='127.0.0.1', max_length=64)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
