# Generated by Django 2.1.1 on 2019-04-20 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0021_system_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='tou.jpg', upload_to=''),
        ),
    ]
