# Generated by Django 2.1.1 on 2019-04-21 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0023_auto_20190421_0018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.ImageField(default='tou.jpg', upload_to=''),
        ),
    ]
