# Generated by Django 2.1.1 on 2019-04-27 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('design', '0024_auto_20190421_0021'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='message', to='design.Article')),
                ('user', models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='design.Users')),
            ],
        ),
    ]
