#-*-coding:utf-8-*-
from django.urls import path,re_path
from . import views

app_name="adminmywork"
urlpatterns = [
    path("login/",views.login,name="login"),
    path("login_check/",views.login_check,name="login_check"),
    path("log_out/",views.log_out,name="log_out"),
    path("index/",views.index,name="index"),
    path('desk/',views.desk,name="desk"),
    path('sort_list/',views.sort,name="sort"),
    path('sort_add/',views.sort_add,name="sort_add"),
    path('sort_save/', views.sort_save, name="sort_save"),
    path('sort_change/', views.sort_change, name="sort_change"),
    path('sort_save2/', views.sort_save2, name="sort_save2"),
    path('sort_delete/',views.sort_delete,name='sort_delete'),
    path('total_del/',views.total_del,name='total_del'),
    path('article_list/',views.article_list,name="article_list"),
    path("article/add/", views.article_add, name="article_add"),
    path("article/save/", views.article_save, name="article_save"),
    path("article/del/", views.article_delete, name="article_delete"),
    path("article/change/", views.article_change, name="article_change"),
    path("article/delall/", views.all_del_article, name="article_delall"),
    path("article/save2/", views.article_save2, name="article_save2"),
    path('article/shenhe/',views.article_shenhe1,name='article_shenhe1'),
    path('article/check/',views.article_check,name='article_check'),
    path('info_admin/',views.info_admin,name="info_admin"),
    path('admin/list/',views.admin_list,name="admin_list"),
    path("admin/add/",views.admin_add,name="admin_add"),
    path('admin/save/',views.admin_save,name="admin_save"),
    path("admin/change/",views.admin_change,name="admin_change"),
    path("admin/save2/",views.admin_save2,name="admin_save2"),
    path("admin/del/",views.admin_del,name="admin_del"),
    path("admin/alldel/",views.admin_alldel,name="admin_alldel"),
    path('admin/usercheck/',views.user_check,name="user_check"),
    path('admin/phonecheck/',views.phone_check,name='phone_check'),
    path('connect/',views.connect,name='connect'),
    path('connect/del/',views.connect_del,name="connect_del"),
    path('connect/alldel/',views.connect_alldel,name="connect_alldel"),
    path('connect/show/',views.connect_show,name="connect_show"),
    path("aa/",views.aa,name="aa"),
    path('system_log/',views.system_log,name='system_log'),
    path('systemlog_delete/',views.systemlog_delete,name='systemlog_delete'),
    path('system_log_alldel/',views.system_log_alldel,name='system_log_alldel'),
]